export const modalConstants = {
	SHOW_OBJECT_DETAILS: "SHOW_OBJECT_DETAILS",
	HIDE_OBJECT_DETAILS: "HIDE_OBJECT_DETAILS",

	ALLOW_OBJECT_DETAILS_INPUT_FIELDS: "ALLOW_OBJECT_DETAILS_INPUT_FIELDS",

	SHOW_OBJECT_ADMIN_DETAILS: "SHOW_OBJECT_ADMIN_DETAILS",
	HIDE_OBJECT_ADMIN_DETAILS: "HIDE_OBJECT_ADMIN_DETAILS",

	ALLOW_OBJECT_ADMIN_DETAILS_INPUT_FIELDS: "ALLOW_OBJECT_ADMIN_DETAILS_INPUT_FIELDS",

	SHOW_WAITER_DETAILS: "SHOW_WAITER_DETAILS",
	HIDE_WAITER_DETAILS: "HIDE_WAITER_DETAILS",

	ALLOW_WAITER_DETAILS_INPUT_FIELDS: "ALLOW_WAITER_DETAILS_INPUT_FIELDS",

	SHOW_DELIVERER_REQUEST_DETAILS: "SHOW_DELIVERER_REQUEST_DETAILS",
	HIDE_DELIVERER_REQUEST_DETAILS: "HIDE_DELIVERER_REQUEST_DETAILS",
	SHOW_DELIVERER_REQUEST_REJECT_WINDOW: "SHOW_DELIVERER_REQUEST_REJECT_WINDOW",
	BACK_FROM_DELIVERER_REQUEST_REJECT_WINDOW: "BACK_FROM_DELIVERER_REQUEST_REJECT_WINDOW",

	SHOW_CREATE_CATEGORY_MODAL: "SHOW_CREATE_CATEGORY_MODAL",
	HIDE_CREATE_CATEGORY_MODAL: "HIDE_CREATE_CATEGORY_MODAL",

	SHOW_CREATE_PRODUCT_MODAL: "SHOW_CREATE_PRODUCT_MODAL",
	HIDE_CREATE_PRODUCT_MODAL: "HIDE_CREATE_PRODUCT_MODAL",

	SHOW_UPDATE_PRODUCT_MODAL: "SHOW_UPDATE_PRODUCT_MODAL",
	HIDE_UPDATE_PRODUCT_MODAL: "HIDE_UPDATE_PRODUCT_MODAL",

	SHOW_DELIVERER_DETAILS: "SHOW_DELIVERER_DETAILS",
	HIDE_DELIVERER_DETAILS: "HIDE_DELIVERER_DETAILS",

	SHOW_ORDER_ITEM_DETAILS_MODAL: "SHOW_ORDER_ITEM_DETAILS_MODAL",
	HIDE_ORDER_ITEM_DETAILS_MODAL: "HIDE_ORDER_ITEM_DETAILS_MODAL",

	SHOW_ACCEPT_UNCONFIRMED_ORDER_MODAL:"SHOW_ACCEPT_UNCONFIRMED_ORDER_MODAL",
	HIDE_ACCEPT_UNCONFIRMED_ORDER_MODAL:"SHOW_HIDE_UNCONFIRMED_ORDER_MODAL",

	SHOW_ORDER_DETAILS_MODAL:"SHOW_ORDER_DETAILS_MODAL",
	HIDE_ORDER_DETAILS_MODAL:"HIDE_ORDER_DETAILS_MODAL",
};
