export const modalConstants = {
	SHOW_OBJECT_DETAILS: "SHOW_OBJECT_DETAILS",
	HIDE_OBJECT_DETAILS: "HIDE_OBJECT_DETAILS",

	ALLOW_OBJECT_DETAILS_INPUT_FIELDS: "ALLOW_OBJECT_DETAILS_INPUT_FIELDS",

	SHOW_OBJECT_ADMIN_DETAILS: "SHOW_OBJECT_ADMIN_DETAILS",
	HIDE_OBJECT_ADMIN_DETAILS: "HIDE_OBJECT_ADMIN_DETAILS",

	ALLOW_OBJECT_ADMIN_DETAILS_INPUT_FIELDS: "ALLOW_OBJECT_ADMIN_DETAILS_INPUT_FIELDS",

	SHOW_WAITER_DETAILS: "SHOW_WAITER_DETAILS",
	HIDE_WAITER_DETAILS: "HIDE_WAITER_DETAILS",

	ALLOW_WAITER_DETAILS_INPUT_FIELDS: "ALLOW_WAITER_DETAILS_INPUT_FIELDS",
};
