export const objectConstants = {
	OBJECT_CREATE_REQUEST: "OBJECT_CREATE_REQUEST",
	OBJECT_CREATE_SUCCESS: "OBJECT_CREATE_SUCCESS",
	OBJECT_CREATE_FAILURE: "OBJECT_CREATE_FAILURE",

	SET_OBJECTS_REQUEST: "SET_OBJECTS",
	SET_OBJECTS_ERROR: "SET_OBJECTS_ERROR",
	SET_OBJECTS_SUCCESS: "SET_OBJECTS_SUCCESS",
};
