export const objectConstants = {
	OBJECT_CREATE_REQUEST: "OBJECT_CREATE_REQUEST",
	OBJECT_CREATE_SUCCESS: "OBJECT_CREATE_SUCCESS",
	OBJECT_CREATE_FAILURE: "OBJECT_CREATE_FAILURE",

	OBJECT_UPDATE_REQUEST: "OBJECT_UPDATE_REQUEST",
	OBJECT_UPDATE_SUCCESS: "OBJECT_UPDATE_SUCCESS",
	OBJECT_UPDATE_FAILURE: "OBJECT_UPDATE_FAILURE",

	OBJECT_INFO_REQUEST: "OBJECT_INFO_REQUEST",
	OBJECT_INFO_SUCCESS: "OBJECT_INFO_SUCCESS",
	OBJECT_INFO_FAILURE: "OBJECT_INFO_FAILURE",

	OBJECT_IMAGE_SELECTED: "OBJECT_IMAGE_SELECTED",
	OBJECT_IMAGE_DESELECTED: "OBJECT_IMAGE_DESELECTED",

	OBJECT_IMAGE_CHANGE_REQUEST: "OBJECT_IMAGE_CHANGE_REQUEST",
	OBJECT_IMAGE_CHANGE_SUCCESS: "OBJECT_IMAGE_CHANGE_SUCCESS",
	OBJECT_IMAGE_CHANGE_FAILURE: "OBJECT_IMAGE_CHANGE_FAILURE",

	SET_OBJECTS_REQUEST: "SET_OBJECTS_REQUEST",
	SET_OBJECTS_ERROR: "SET_OBJECTS_ERROR",
	SET_OBJECTS_SUCCESS: "SET_OBJECTS_SUCCESS",

	OBJECT_ACTIVATION_REQUEST: "OBJECT_ACTIVATION_REQUEST",
	OBJECT_ACTIVATION_SUCCESS: "OBJECT_ACTIVATION_SUCCESS",
	OBJECT_ACTIVATION_FAILURE: "OBJECT_ACTIVATION_FAILURE",

	OBJECT_DEACTIVATION_REQUEST: "OBJECT_DEACTIVATION_REQUEST",
	OBJECT_DEACTIVATION_SUCCESS: "OBJECT_DEACTIVATION_SUCCESS",
	OBJECT_DEACTIVATION_FAILURE: "OBJECT_DEACTIVATION_FAILURE",

	OBJECT_BLOCKING_REQUEST: "OBJECT_BLOCKING_REQUEST",
	OBJECT_BLOCKING_SUCCESS: "OBJECT_BLOCKING_SUCCESS",
	OBJECT_BLOCKING_FAILURE: "OBJECT_BLOCKING_FAILURE",

	OBJECT_UNBLOCKING_REQUEST: "OBJECT_UNBLOCKING_REQUEST",
	OBJECT_UNBLOCKING_SUCCESS: "OBJECT_UNBLOCKING_SUCCESS",
	OBJECT_UNBLOCKING_FAILURE: "OBJECT_UNBLOCKING_FAILURE",

	GENERATE_SELF_ORDERING_TOKEN_SUCCESS:"GENERATE_SELF_ORDERING_TOKEN_SUCCESS",
	GENERATE_SELF_ORDERING_TOKEN_FAILURE:"GENERATE_SELF_ORDERING_TOKEN_FAILURE",
};
