export const orderConstants = {
	ADD_PRODUCT_TO_ORDER: "ADD_PRODUCT_TO_ORDER",
	REMOVE_PRODUCT_FROM_ORDER: "REMOVE_PRODUCT_FROM_ORDER",
	SET_PRODUCT_COUNT_TO_ORDER: "SET_PRODUCT_COUNT_TO_ORDER",

	SET_CREATE_ORDER_PAGE: "SET_CREATE_ORDER_PAGE",
	CREATE_ORDER_SELECT_TABLE: "CREATE_ORDER_SELECT_TABLE",
	SET_ADDRESS_AND_TIME_CREATE_ORDER: "SET_ADDRESS_AND_TIME_CREATE_ORDER",
	SET_CREATE_ORDER_TYPE: "SET_CREATE_ORDER_TYPE",

	ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
	ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
	ORDER_CREATE_FAILURE: "ORDER_CREATE_FAILURE",

	GET_UNCONFIRMED_ORDER_SUCCESS:"GET_UNCONFIRMED_ORDER_SUCCESS",
	GET_UNCONFIRMED_ORDER_FAILURE:"GET_UNCONFIRMED_ORDER_FAILURE",

	REJECT_ORDER_SUCCESS:"REJECT_ORDER_SUCCESS",
	REJECT_ORDER_FAILURE:"REJECT_ORDER_FAILURE",

	ACCEPT_UNCONFIRMED_ORDER_ESTIMATED_TIME_FAILURE:"ACCEPT_UNCONFIRMED_ORDER_ESTIMATED_TIME_FAILURE",

	ACCEPT_UNCONFIRMED_ORDER_SUCCESS: "ACCEPT_UNCONFIRMED_ORDER_SUCCESS",
	ACCEPT_UNCONFIRMED_ORDER_FAILURE:"ACCEPT_UNCONFIRMED_ORDER_SUCCESS",
};
