export const orderConstants = {
	ADD_PRODUCT_TO_ORDER: "ADD_PRODUCT_TO_ORDER",
	REMOVE_PRODUCT_FROM_ORDER: "REMOVE_PRODUCT_FROM_ORDER",
	SET_PRODUCT_COUNT_TO_ORDER: "SET_PRODUCT_COUNT_TO_ORDER",

	SET_CREATE_ORDER_PAGE: "SET_CREATE_ORDER_PAGE",
	CREATE_ORDER_SELECT_TABLE: "CREATE_ORDER_SELECT_TABLE",
	SET_ADDRESS_AND_TIME_CREATE_ORDER: "SET_ADDRESS_AND_TIME_CREATE_ORDER",
	SET_CREATE_ORDER_TYPE: "SET_CREATE_ORDER_TYPE",
};
