export const productConstants = {
	CATEGORY_CREATE_REQUEST: "CATEGORY_CREATE_REQUEST",
	CATEGORY_CREATE_SUCCESS: "CATEGORY_CREATE_SUCCESS",
	CATEGORY_CREATE_FAILURE: "CATEGORY_CREATE_FAILURE",

	SET_CATEGORIES_REQUEST: "SET_CATEGORIES_REQUEST",
	SET_CATEGORIES_ERROR: "SET_CATEGORIES_ERROR",
	SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",

	SET_PRODUCT_TYPES_REQUEST: "SET_PRODUCT_TYPES_REQUEST",
	SET_PRODUCT_TYPES_ERROR: "SET_PRODUCT_TYPES_ERROR",
	SET_PRODUCT_TYPES_SUCCESS: "SET_PRODUCT_TYPES_SUCCESS",

	CREATE_PRODUCT_IMAGE_SELECTED: "CREATE_PRODUCT_IMAGE_SELECTED",
	CREATE_PRODUCT_IMAGE_DESELECTED: "CREATE_PRODUCT_IMAGE_DESELECTED",
	CREATE_PRODUCT_SUBMIT_FIRST_PAGE: "CREATE_PRODUCT_SUBMIT_FIRST_PAGE",
	CREATE_PRODUCT_BACK_TO_FIRST_PAGE: "CREATE_PRODUCT_BACK_TO_FIRST_PAGE",

	PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
	PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
	PRODUCT_CREATE_FAILURE: "PRODUCT_CREATE_FAILURE",

	SET_PRODUCTS_REQUEST: "SET_PRODUCTS_REQUEST",
	SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",
	SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",

	CREATE_PRODUCT_MODAL_HIDE_ERROR: "CREATE_PRODUCT_MODAL_HIDE_ERROR",

	FILTER_PRODUCTS_BY_CATEGORY: "FILTER_PRODUCTS_BY_CATEGORY",
	DISABLE_PRODUCTS_FILTER: "DISABLE_PRODUCTS_FILTER",

	PRODUCT_TOGGLE_DETAILS: "PRODUCT_TOGGLE_DETAILS",

	PRODUCT_IMAGE_CHANGE_REQUEST: "PRODUCT_IMAGE_CHANGE_REQUEST",
	PRODUCT_IMAGE_CHANGE_SUCCESS: "PRODUCT_IMAGE_CHANGE_SUCCESS",
	PRODUCT_IMAGE_CHANGE_FAILURE: "PRODUCT_IMAGE_CHANGE_FAILURE",

	UPDATE_PRODUCT_SUBMIT_FIRST_PAGE: "UPDATE_PRODUCT_SUBMIT_FIRST_PAGE",
	UPDATE_PRODUCT_BACK_TO_FIRST_PAGE: "UPDATE_PRODUCT_BACK_TO_FIRST_PAGE",

	PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
	PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
	PRODUCT_UPDATE_FAILURE: "PRODUCT_UPDATE_FAILURE",

	UPDATE_PRODUCT_MODAL_HIDE_ERROR: "UPDATE_PRODUCT_MODAL_HIDE_ERROR",

	PRODUCT_DELETE_SUCCESS:"PRODUCT_DELETE_SUCCESS",
	PRODUCT_DELETE_FAILURE:"PRODUCT_DELETE_FAILURE",

	HIDE_PRODUCT_ALERT_MESSAGE:"HIDE_PRODUCT_ALERT_MESSAGE",

	CATEGORY_DELETE_SUCCESS:"CATEGORY_DELETE_SUCCESS",
	CATEGORY_DELETE_FAILURE:"CATEGORY_DELETE_FAILURE"
};
