export const tableConstants = {
	TABLE_CREATE_REQUEST: "TABLE_CREATE_REQUEST",
	TABLE_CREATE_SUCCESS: "TABLE_CREATE_SUCCESS",
	TABLE_CREATE_FAILURE: "TABLE_CREATE_FAILURE",

	SET_TABLES_REQUEST: "SET_TABLES_REQUEST",
	SET_TABLES_ERROR: "SET_TABLES_ERROR",
	SET_TABLES_SUCCESS: "SET_TABLES_SUCCESS",

	TABLE_DELETE_REQUEST: "TABLE_DELETE_REQUEST",
	TABLE_DELETE_SUCCESS: "TABLE_DELETE_SUCCESS",
	TABLE_DELETE_FAILURE: "TABLE_DELETE_FAILURE",
};
