export const userConstants = {
	OBJECT_ADMIN_CREATE_REQUEST: "OBJECT_ADMIN_CREATE_REQUEST",
	OBJECT_ADMIN_CREATE_SUCCESS: "OBJECT_ADMIN_CREATE_SUCCESS",
	OBJECT_ADMIN_CREATE_FAILURE: "OBJECT_ADMIN_CREATE_FAILURE",

	OBJECT_ADMIN_UPDATE_REQUEST: "OBJECT_ADMIN_UPDATE_REQUEST",
	OBJECT_ADMIN_UPDATE_SUCCESS: "OBJECT_ADMIN_UPDATE_SUCCESS",
	OBJECT_ADMIN_UPDATE_FAILURE: "OBJECT_ADMIN_UPDATE_FAILURE",

	OBJECT_ADMIN_DELETE_REQUEST: "OBJECT_ADMIN_DELETE_REQUEST",
	OBJECT_ADMIN_DELETE_SUCCESS: "OBJECT_ADMIN_DELETE_SUCCESS",
	OBJECT_ADMIN_DELETE_FAILURE: "OBJECT_ADMIN_DELETE_FAILURE",

	SET_OBJECT_ADMINS_REQUEST: "SET_OBJECT_ADMINS_REQUEST",
	SET_OBJECT_ADMINS_ERROR: "SET_OBJECT_ADMINS_ERROR",
	SET_OBJECT_ADMINS_SUCCESS: "SET_OBJECT_ADMINS_SUCCESS",

	SET_DELIVERER_REQUEST: "SET_DELIVERER_REQUEST",
	SET_DELIVERER_REQUEST_ERROR: "SET_DELIVERER_REQUEST_ERROR",
	SET_DELIVERER_REQUEST_SUCCESS: "SET_DELIVERER_REQUEST_SUCCESS",

	ACCEPT_DELIVERER_REQUEST_SUCCESS: "ACCEPT_DELIVERER_REQUEST_SUCCESS",
	ACCEPT_DELIVERER_REQUEST_FAILURE: "ACCEPT_DELIVERER_REQUEST_FAILURE",

	REJECT_DELIVERER_REQUEST_SUCCESS: "REJECT_DELIVERER_REQUEST_SUCCESS",
	REJECT_DELIVERER_REQUEST_FAILURE: "REJECT_DELIVERER_REQUEST_FAILURE",
	HIDE_FAILURE_ALERT_REJECT_DELIVERY_REQUEST: "HIDE_FAILURE_ALERT_REJECT_DELIVERY_REQUEST",

	WAITER_CREATE_REQUEST: "WAITER_CREATE_REQUEST",
	WAITER_CREATE_SUCCESS: "WAITER_CREATE_SUCCESS",
	WAITER_CREATE_FAILURE: "WAITER_CREATE_FAILURE",

	WAITER_UPDATE_REQUEST: "WAITER_UPDATE_REQUEST",
	WAITER_UPDATE_SUCCESS: "WAITER_UPDATE_SUCCESS",
	WAITER_UPDATE_FAILURE: "WAITER_UPDATE_FAILURE",

	SET_WAITERS_REQUEST: "SET_WAITERS_REQUEST",
	SET_WAITERS_ERROR: "SET_WAITERS_ERROR",
	SET_WAITERS_SUCCESS: "SET_WAITERS_SUCCESS",

	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	INACTIVE_USER_EMAIL_REQUEST: "INACTIVE_USER_EMAIL_REQUEST",

	RESEND_ACTIVATION_LINK_REQUEST: "RESEND_ACTIVATION_LINK_REQUEST",
	RESEND_ACTIVATION_LINK_SUCCESS: "RESEND_ACTIVATION_LINK_SUCCESS",
	RESEND_ACTIVATION_LINK_FAILURE: "RESEND_ACTIVATION_LINK_FAILURE",

	FIRST_ACTIVATION_PASSWORD_CHANGE_REQUEST: "FIRST_ACTIVATION_PASSWORD_CHANGE_REQUEST",
	FIRST_ACTIVATION_PASSWORD_CHANGE_SUCCESS: "FIRST_ACTIVATION_PASSWORD_CHANGE_SUCCESS",
	FIRST_ACTIVATION_PASSWORD_CHANGE_FAILURE: "FIRST_ACTIVATION_PASSWORD_CHANGE_FAILURE",

	RESET_PASSWORD_LINK_REQUEST: "RESET_PASSWORD_LINK_REQUEST",
	RESET_PASSWORD_LINK_SUCCESS: "RESET_PASSWORD_LINK_SUCCESS",
	RESET_PASSWORD_LINK_FAILURE: "RESET_PASSWORD_LINK_FAILURE",

	RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
	RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
	RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

	SET_DELIVERERS_REQUEST: "SET_DELIVERERS_REQUEST",
	SET_DELIVERERS_ERROR: "SET_DELIVERERS_ERROR",
	SET_DELIVERERS_SUCCESS: "SET_DELIVERERS_SUCCESS",

	DELIVERER_ACTIVATION_REQUEST: "DELIVERER_ACTIVATION_REQUEST",
	DELIVERER_ACTIVATION_SUCCESS: "DELIVERER_ACTIVATION_SUCCESS",
	DELIVERER_ACTIVATION_FAILURE: "DELIVERER_ACTIVATION_FAILURE",

	HIDE_UPDATE_DELIVERER_ALERTS: "HIDE_UPDATE_DELIVERER_ALERTS",
};
