export const userConstants = {
	OBJECT_ADMIN_CREATE_REQUEST: "OBJECT_ADMIN_CREATE_REQUEST",
	OBJECT_ADMIN_CREATE_SUCCESS: "OBJECT_ADMIN_CREATE_SUCCESS",
	OBJECT_ADMIN_CREATE_FAILURE: "OBJECT_ADMIN_CREATE_FAILURE",

	OBJECT_ADMIN_UPDATE_REQUEST: "OBJECT_ADMIN_UPDATE_REQUEST",
	OBJECT_ADMIN_UPDATE_SUCCESS: "OBJECT_ADMIN_UPDATE_SUCCESS",
	OBJECT_ADMIN_UPDATE_FAILURE: "OBJECT_ADMIN_UPDATE_FAILURE",

	SET_OBJECT_ADMINS_REQUEST: "SET_OBJECT_ADMINS_REQUEST",
	SET_OBJECT_ADMINS_ERROR: "SET_OBJECT_ADMINS_ERROR",
	SET_OBJECT_ADMINS_SUCCESS: "SET_OBJECT_ADMINS_SUCCESS",

	WAITER_CREATE_REQUEST: "WAITER_CREATE_REQUEST",
	WAITER_CREATE_SUCCESS: "WAITER_CREATE_SUCCESS",
	WAITER_CREATE_FAILURE: "WAITER_CREATE_FAILURE",

	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	INACTIVE_USER_EMAIL_REQUEST: "INACTIVE_USER_EMAIL_REQUEST",

	RESEND_ACTIVATION_LINK_REQUEST: "RESEND_ACTIVATION_LINK_REQUEST",
	RESEND_ACTIVATION_LINK_SUCCESS: "RESEND_ACTIVATION_LINK_SUCCESS",
	RESEND_ACTIVATION_LINK_FAILURE: "RESEND_ACTIVATION_LINK_FAILURE",

	FIRST_ACTIVATION_PASSWORD_CHANGE_REQUEST: "FIRST_ACTIVATION_PASSWORD_CHANGE_REQUEST",
	FIRST_ACTIVATION_PASSWORD_CHANGE_SUCCESS: "FIRST_ACTIVATION_PASSWORD_CHANGE_SUCCESS",
	FIRST_ACTIVATION_PASSWORD_CHANGE_FAILURE: "FIRST_ACTIVATION_PASSWORD_CHANGE_FAILURE",
	
	HIDE_OBJECT_ADMIN_EDIT_SUCCESS: "HIDE_OBJECT_ADMIN_EDIT_SUCCESS",
	HIDE_OBJECT_ADMIN_EDIT_FAILURE: "HIDE_OBJECT_ADMIN_EDIT_FAILURE",

	RESET_PASSWORD_LINK_REQUEST: "RESET_PASSWORD_LINK_REQUEST",
	RESET_PASSWORD_LINK_SUCCESS: "RESET_PASSWORD_LINK_SUCCESS",
	RESET_PASSWORD_LINK_FAILURE: "RESET_PASSWORD_LINK_FAILURE",
};
