export const userConstants = {
	OBJECT_ADMIN_CREATE_REQUEST: "OBJECT_ADMIN_CREATE_REQUEST",
	OBJECT_ADMIN_CREATE_SUCCESS: "OBJECT_ADMIN_CREATE_SUCCESS",
	OBJECT_ADMIN_CREATE_FAILURE: "OBJECT_ADMIN_CREATE_FAILURE",

	SET_OBJECT_ADMINS_REQUEST: "SET_OBJECT_ADMINS_REQUEST",
	SET_OBJECT_ADMINS_ERROR: "SET_OBJECT_ADMINS_ERROR",
	SET_OBJECT_ADMINS_SUCCESS: "SET_OBJECT_ADMINS_SUCCESS",
};
