export const authConstants = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	LOGIN_VALIDATION_FAILURE: "LOGIN_VALIDATION_FAILURE",

	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

	CREATE_EMPLOYMENT_REQUEST_REQUEST: "CREATE_EMPLOYMENT_REQUEST_REQUEST",
	CREATE_EMPLOYMENT_REQUEST_SUCCESS: "CREATE_EMPLOYMENT_REQUEST_SUCCESS",
	CREATE_EMPLOYMENT_REQUEST_FAILURE: "CREATE_EMPLOYMENT_REQUEST_FAILURE",
	CREATE_EMPLOYMENT_REQUEST_VALIDATION_FAILURE: "CREATE_EMPLOYMENT_REQUEST_VALIDATION_FAILURE",
};
