export const authConstants = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	LOGIN_VALIDATION_FAILURE: "LOGIN_VALIDATION_FAILURE",
	LOGIN_USER_NOT_ACTIVE: "LOGIN_USER_NOT_ACTIVE",

	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

	CREATE_EMPLOYMENT_REQUEST_REQUEST: "CREATE_EMPLOYMENT_REQUEST_REQUEST",
	CREATE_EMPLOYMENT_REQUEST_SUCCESS: "CREATE_EMPLOYMENT_REQUEST_SUCCESS",
	CREATE_EMPLOYMENT_REQUEST_FAILURE: "CREATE_EMPLOYMENT_REQUEST_FAILURE",
	CREATE_EMPLOYMENT_REQUEST_VALIDATION_FAILURE: "CREATE_EMPLOYMENT_REQUEST_VALIDATION_FAILURE",

	INACTIVE_USER_EMAIL_SUCCESS: "INACTIVE_USER_EMAIL_SUCCESS",
	INACTIVE_USER_EMAIL_FAILURE: "INACTIVE_USER_EMAIL_FAILURE",

	RESEND_ACTIVATION_LINK_REQUEST: "RESEND_ACTIVATION_LINK_REQUEST",
	RESEND_ACTIVATION_LINK_SUCCESS: "RESEND_ACTIVATION_LINK_SUCCESS",
	RESEND_ACTIVATION_LINK_FAILURE: "RESEND_ACTIVATION_LINK_FAILURE",

	RESET_PASSWORD_LINK_REQUEST: "RESET_PASSWORD_LINK_REQUEST",
	RESET_PASSWORD_LINK_SUCCESS: "RESET_PASSWORD_LINK_SUCCESS",
	RESET_PASSWORD_LINK_FAILURE: "RESET_PASSWORD_LINK_FAILURE",
};
