export const orderConstants = {
	SET_PENDING_ORDERS_REQUEST: "SET_PENDING_ORDERS_REQUEST",
	SET_PENDING_ORDERS_SUCCESS: "SET_PENDING_ORDERS_SUCCESS",
	SET_PENDING_ORDERS_FAILURE: "SET_PENDING_ORDERS_FAILURE",
};
