export const orderConstants = {
	SET_ACCEPTED_ORDERS_REQUEST: "SET_ACCEPTED_ORDERS_REQUEST",
	SET_ACCEPTED_ORDERS_SUCCESS: "SET_ACCEPTED_ORDERS_SUCCESS",
	SET_ACCEPTED_ORDERS_FAILURE: "SET_ACCEPTED_ORDERS_FAILURE",

	SET_PENDING_ORDERS_REQUEST: "SET_PENDING_ORDERS_REQUEST",
	SET_PENDING_ORDERS_SUCCESS: "SET_PENDING_ORDERS_SUCCESS",
	SET_PENDING_ORDERS_FAILURE: "SET_PENDING_ORDERS_FAILURE",

	ACCEPT_ORDER_REQUEST: "ACCEPT_ORDER_REQUEST",
	ACCEPT_ORDER_SUCCESS: "ACCEPT_ORDER_SUCCESS",
	ACCEPT_ORDER_FAILURE: "ACCEPT_ORDER_FAILURE",
};
