export const orderConstants = {
    "SHOW_ORDER_ITEM_DETAILS":"SHOW_ORDER_ITEM_DETAILS",
    "HIDE_ORDER_ITEM_DETAILS":"HIDE_ORDER_ITEM_DETAILS",

    "CHOOSE_ORDER_TYPE":"CHOOSE_ORDER_TYPE",
    "RESET_ORDER":"RESET_ORDER",

    "ADD_PRODUCT_TO_SHOPPING_CART":"ADD_PRODUCT_TO_SHOPPING_CART",

    "SET_ORDER_ITEM_COUNT":"SET_ORDER_ITEM_COUNT",

    "REMOVE_ORDER_ITEM_FROM_SHOPPING_CART":"REMOVE_ORDER_ITEM_FROM_SHOPPING_CART",

    "FINISH_ORDER":"FINISH_ORDER",

    "ORDER_CREATE_SUCCESS":"ORDER_CREATE_SUCCESS",
    "ORDER_CREATE_FAILURE":"ORDER_CREATE_FAILURE",
}