export const orderConstants = {
    "SHOW_ORDER_ITEM_DETAILS":"SHOW_ORDER_ITEM_DETAILS",
    "HIDE_ORDER_ITEM_DETAILS":"HIDE_ORDER_ITEM_DETAILS",

    "CHOOSE_ORDER_TYPE":"CHOOSE_ORDER_TYPE",
    "RESET_ORDER":"RESET_ORDER",
}