export const productConstants = {
	SET_PRODUCTS_REQUEST: "SET_PRODUCTS_REQUEST",
	SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",
	SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
	
	SET_CATEGORIES_REQUEST: "SET_CATEGORIES_REQUEST",
	SET_CATEGORIES_ERROR: "SET_CATEGORIES_ERROR",
	SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",

	DISABLE_PRODUCTS_FILTER:"DISABLE_PRODUCTS_FILTER",
	FILTER_PRODUCTS_BY_CATEGORY:"FILTER_PRODUCTS_BY_CATEGORY",
};
