export const feedbackConstants = {
	RATE_DELIVERER_REQUEST: "RATE_DELIVERER_REQUEST",
	RATE_DELIVERER_SUCCESS: "RATE_DELIVERER_SUCCESS",
	RATE_DELIVERER_FAILURE: "RATE_DELIVERER_FAILURE",

	RATE_OBJECT_REQUEST: "RATE_OBJECT_REQUEST",
	RATE_OBJECT_SUCCESS: "RATE_OBJECT_SUCCESS",
	RATE_OBJECT_FAILURE: "RATE_OBJECT_FAILURE",
};
