export const objectConstants = {
	FIND_ALL_OBJECTS_REQUEST: "FIND_ALL_OBJECTS_REQUEST",
	FIND_ALL_OBJECTS_SUCCESS: "FIND_ALL_OBJECTS_SUCCESS",
	FIND_ALL_OBJECTS_FAILURE: "FIND_ALL_OBJECTS_FAILURE",
};
