export const objectConstants = {
	FIND_ALL_OBJECTS_REQUEST: "FIND_ALL_OBJECTS_REQUEST",
	FIND_ALL_OBJECTS_SUCCESS: "FIND_ALL_OBJECTS_SUCCESS",
	FIND_ALL_OBJECTS_FAILURE: "FIND_ALL_OBJECTS_FAILURE",

	FIND_FAVOURITE_OBJECTS_REQUEST: "FIND_FAVOURITE_OBJECTS_REQUEST",
	FIND_FAVOURITE_OBJECTS_SUCCESS: "FIND_FAVOURITE_OBJECTS_SUCCESS",
	FIND_FAVOURITE_OBJECTS_FAILURE: "FIND_FAVOURITE_OBJECTS_FAILURE",

	GET_OBJECT_DETAILS_REQUEST: "GET_OBJECT_DETAILS_REQUEST",
	GET_OBJECT_DETAILS_SUCCESS: "GET_OBJECT_DETAILS_SUCCESS",
	GET_OBJECT_DETAILS_FAILURE: "GET_OBJECT_DETAILS_FAILURE",

	GET_OBJECT_CATEGORIES_REQUEST: "GET_OBJECT_CATEGORIES_REQUEST",
	GET_OBJECT_CATEGORIES_SUCCESS: "GET_OBJECT_CATEGORIES_SUCCESS",
	GET_OBJECT_CATEGORIES_FAILURE: "GET_OBJECT_CATEGORIES_FAILURE",

	FIND_PRODUCTS_BY_CATEGORY: "FIND_PRODUCTS_BY_CATEGORY",

	GET_OBJECT_PRODUCTS_REQUEST: "GET_OBJECT_PRODUCTS_REQUEST",
	GET_OBJECT_PRODUCTS_SUCCESS: "GET_OBJECT_PRODUCTS_SUCCESS",
	GET_OBJECT_PRODUCTS_FAILURE: "GET_OBJECT_PRODUCTS_FAILURE",
};
