export const orderConstants = {
	ADD_PRODUCT_TO_ORDER: "ADD_PRODUCT_TO_ORDER",
	REMOVE_PRODUCT_FROM_ORDER: "REMOVE_PRODUCT_FROM_ORDER",
	SET_PRODUCT_COUNT_TO_ORDER: "SET_PRODUCT_COUNT_TO_ORDER",
	SET_DELIVERY_ADDRESS_TO_ORDER: "SET_DELIVERY_ADDRESS_TO_ORDER",

	ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
	ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
	ORDER_CREATE_FAILURE: "ORDER_CREATE_FAILURE",
};
