export const orderConstants = {
	ADD_PRODUCT_TO_ORDER: "ADD_PRODUCT_TO_ORDER",
	REMOVE_PRODUCT_FROM_ORDER: "REMOVE_PRODUCT_FROM_ORDER",
	SET_PRODUCT_COUNT_TO_ORDER: "SET_PRODUCT_COUNT_TO_ORDER",
	SET_DELIVERY_ADDRESS_TO_ORDER: "SET_DELIVERY_ADDRESS_TO_ORDER",

	ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
	ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
	ORDER_CREATE_FAILURE: "ORDER_CREATE_FAILURE",

	SET_QR_CODE_SCANNED_DATA:"SET_QR_CODE_SCANNED_DATA",

	GET_ORDER_HISTORY_SUCCESS: "GET_ORDER_HISTORY_SUCCESS",
	GET_ORDER_HISTORY_FAILURE: "GET_ORDER_HISTORY_FAILURE",

	GET_PENDING_ORDERS_SUCCESS:"GET_PENDING_ORDERS_SUCCESS",
	GET_PENDING_ORDERS_FAILURE:"GET_PENDING_ORDERS_FAILURE",
};
