export const productConstants = {
	GET_OBJECT_CATEGORIES_REQUEST: "GET_OBJECT_CATEGORIES_REQUEST",
	GET_OBJECT_CATEGORIES_SUCCESS: "GET_OBJECT_CATEGORIES_SUCCESS",
	GET_OBJECT_CATEGORIES_FAILURE: "GET_OBJECT_CATEGORIES_FAILURE",

	FIND_PRODUCTS_BY_CATEGORY: "FIND_PRODUCTS_BY_CATEGORY",

	GET_OBJECT_PRODUCTS_REQUEST: "GET_OBJECT_PRODUCTS_REQUEST",
	GET_OBJECT_PRODUCTS_SUCCESS: "GET_OBJECT_PRODUCTS_SUCCESS",
	GET_OBJECT_PRODUCTS_FAILURE: "GET_OBJECT_PRODUCTS_FAILURE",
};
