export const userConstants = {
	REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
	REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
	REGISTRATION_FAILURE: "REGISTRATION_FAILURE",

	USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
	USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
	USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",

	EDIT_USER_PROFILE_REQUEST: "EDIT_USER_PROFILE_REQUEST",
	EDIT_USER_PROFILE_SUCCESS: "EDIT_USER_PROFILE_SUCCESS",
	EDIT_USER_PROFILE_FAILURE: "EDIT_USER_PROFILE_FAILURE",
};
