export const userConstants = {
	REGISTRATION_REQUEST: "REGISTRATION_REQUEST",
	REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
	REGISTRATION_FAILURE: "REGISTRATION_FAILURE",

	USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
	USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
	USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",

	EDIT_USER_PROFILE_REQUEST: "EDIT_USER_PROFILE_REQUEST",
	EDIT_USER_PROFILE_SUCCESS: "EDIT_USER_PROFILE_SUCCESS",
	EDIT_USER_PROFILE_FAILURE: "EDIT_USER_PROFILE_FAILURE",

	SET_USER_ADDRESSES_REQUEST: "SET_USER_ADDRESSES_REQUEST",
	SET_USER_ADDRESSES_SUCCESS: "SET_USER_ADDRESSES_SUCCESS",
	SET_USER_ADDRESSES_FAILURE: "SET_USER_ADDRESSES_FAILURE",

	REMOVE_USER_ADDRESS_REQUEST: "REMOVE_USER_ADDRESS_REQUEST",
	REMOVE_USER_ADDRESS_SUCCESS: "REMOVE_USER_ADDRESS_SUCCESS",
	REMOVE_USER_ADDRESS_FAILURE: "REMOVE_USER_ADDRESS_FAILURE",

	ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
	ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
	ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
};
